version: "3.3"

services:
  webserver:
    image: "glud/moodle:v1"
    networks:
      - backend
      - reverse_proxy
    depends_on:
      - db
    volumes:
      - www_root:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./config.php:/var/www/html/config.php
      - www_moodle:/var/www/
      - ./apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf
    environment:
      MOODLE_URL: "https://cursos.glud.org"
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: "cursos.glud.org"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=reverse_proxy"
        - "traefik.http.routers.moodle.entrypoints=websecure"
        - "traefik.http.routers.moodle.rule=Host(`cursos.glud.org`)"
        - "traefik.http.routers.moodle.service=moodle"
        - "traefik.http.services.moodle.loadbalancer.server.port=80"
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]
        
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
    networks:
      - backend
    volumes:
      - dbdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]
      
      
volumes:
  www_root:
  dbdata:
  www_moodle:

networks:
  backend:
  reverse_proxy:
    external: true
